config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'workouts#index'

  resources :workouts do
    resources :exercises, only: [:create, :update, :destroy]
    collection do
      get ':year/:month', to: 'workouts#index', as: 'filtered_workouts', constraints: { year: /\d{4}/, month: /\d{1,2}/ }
      # year: /\d{4}/: :year パラメータは4桁の数字でなければなりません。
      # month: /\d{1,2}/: :month パラメータは1桁または2桁の数字でなければなりません。
    end
  end
    # get 'workouts/:year/:month', to: 'workouts#index', as: 'filtered_workouts'
  # 月と年をパラメータとして受け取れるようにします
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout

  # validates :name, :weight, :reps, :sets, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :workouts, dependent: :destroy
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :exercises, dependent: :destroy
  accepts_nested_attributes_for :exercises, allow_destroy: true
  # ネストされたフォームからExerciseの属性を受け入れ、Workoutを更新する際にExerciseの作成、更新、削除が可能になります。
  has_one_attached :image

  scope :recent, -> { order(date: :desc) }

  validates :date, presence: true, uniqueness: { scope: :user_id }
  # scope: :user_idを追加することで、dateの一意性をuser_idごとに制限します。これにより、同じユーザー内では同じ日付のワークアウトを持つことはできませんが、異なるユーザーでは同じ日付を持つことができます。
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    # devise_parameter_sanitizer.permit(:deviseの処理名, keys: [:許可するキー])
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_workout

  def index
    @exercises = @workout.exercises
  end

  def show
    @exercise = @workout.exercises.find(params[:id])
  end

  def new
    @exercise = @workout.exercises.new
  end

  def create
    @exercise = @workout.exercises.new(exercise_params)
    if @exercise.save
      redirect_to [@workout, @exercise]
    else
      render 'new'
    end
  end

  def edit
    @exercise = @workout.exercises.find(params[:id])
  end

  def update
    @exercise = @workout.exercises.find(params[:id])
    if @exercise.update(exercise_params)
      redirect_to [@workout, @exercise]
    else
      render 'edit'
    end
  end

  def destroy
    @exercise = @workout.exercises.find(params[:id])
    @exercise.destroy
    redirect_to workout_exercises_path(@workout)
  end

  private

  def set_workout
    @workout = Workout.find(params[:workout_id])
  end

  def exercise_params
    params.require(:exercise).permit(:name, :weight, :reps, :sets, :duration, :distance)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :redirect_unless_logged_in, except: :index

  # before_action :authenticate_user! # ユーザーがログインしていることを確認
  #このフィルターにより、ユーザーがログインしていない場合、アクションが実行される前にログインページにリダイレクトされます。
  
  def index
    if user_signed_in?
      if params[:year].present? && params[:month].present?
        selected_year = params[:year].to_i
        selected_month = params[:month].to_i
        Rails.logger.debug "Selected year: #{selected_year}, Selected month: #{selected_month}"
        @workouts = current_user.workouts.where("extract(year from date) = ? AND extract(month from date) = ?", selected_year, selected_month).order(date: :desc).recent
        # @workouts = current_user.workouts.where("extract(year from date) = ? AND extract(month from date) = ?", selected_year, selected_month).recent
      else
        @workouts = current_user.workouts.order(date: :desc).recent
        # @workouts = [] 多分これが表示されない原因だったのだと思う20240606
      end
    else
      @workouts = []
      flash[:alert] = "Please log in to view your workouts."
    end
  end
    #@workouts = current_user.workouts.recent if user_signed_in?
    # 現在ログインしているユーザーに関連する workout オブジェクトをすべて取得します。
    #.recent はスコープメソッドでワークアウトのレコードを新しい順にソートして返す
    #@workouts = Workout.recent
    #@workouts = Workout.all


  def show
    @workout = Workout.find(params[:id])
    @exercises = @workout.exercises
  end

  def new
    @workout = Workout.new
    5.times { @workout.exercises.build }
    #@exercise_count = params[:exercise_count] ? params[:exercise_count].to_i : 1
    #@exercise_count.times { @workout.exercises.build }
    #@workout.exercises.build
  end

  def create
    @workout = Workout.new(workout_params.except(:year, :month)) # yearとmonthを除外
    # @workout = Workout.new(workout_params)
    @workout.user = current_user
    if @workout.save
      redirect_to @workout, notice: 'Workout was successfully created.'
      #redirect_to root_path
      #redirect_to @workout, notice: 'Workout was successfully created.'
    else
      # @exercise_count = workout_params[:exercise_count].to_i 20240605に消した
      render :new
    end
  end

  def edit
    @workout = Workout.find(params[:id])
    (5 - @workout.exercises.size).times { @workout.exercises.build }
  end

  def update
    @workout = Workout.find(params[:id])
    if @workout.update(workout_params)
      redirect_to @workout, notice: 'Workout was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy
    redirect_to workouts_path
  end

  private

  def redirect_unless_logged_in
    redirect_to root_path unless user_signed_in?
  end

  def workout_params
    params.require(:workout).permit(:date, :image, exercises_attributes: [:id, :name, :weight, :reps, :sets, :duration, :_destroy])
    # params.require(:workout).permit(:date, :image, exercises_attributes: [:id, :name, :weight, :reps, :sets, :duration, :distance, :_destroy])
    #params.require(:workout).permit(:date, exercises_attributes: [:id, :name, :weight, :reps, :sets, :duration, :distance, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def japanese_wday(date)
    wdays = %w[日 月 火 水 木 金 土]
    wdays[date.wday]
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/create.html.erb
<h1>Exercises#create</h1>
<p>Find me in app/views/exercises/create.html.erb</p>

app/views/exercises/destroy.html.erb
<h1>Exercises#destroy</h1>
<p>Find me in app/views/exercises/destroy.html.erb</p>

app/views/exercises/edit.html.erb
<h1>Exercises#edit</h1>
<p>Find me in app/views/exercises/edit.html.erb</p>

app/views/exercises/index.html.erb
<h1>Exercises#index</h1>
<p>Find me in app/views/exercises/index.html.erb</p>

app/views/exercises/new.html.erb
<h1>Exercises#new</h1>
<p>Find me in app/views/exercises/new.html.erb</p>

app/views/exercises/show.html.erb
<h1>Exercises#show</h1>
<p>Find me in app/views/exercises/show.html.erb</p>

app/views/exercises/update.html.erb
<h1>Exercises#update</h1>
<p>Find me in app/views/exercises/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkoutApp</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="upper">
      <div class="title">
        <h1><%= link_to "トレーニングNOTE", root_path %></h1>
      </div>
      <% if user_signed_in? %>
      <div class="user-info">
        <span><%= current_user.nickname %>さん、今日もお疲れ様です！</span>
      </div>
        <div class="user_nav grid-6">
          <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "login-button" %>
          <% if @workout && @workout.persisted? %>
          <%# <%= link_to "投稿する", new_workout_exercise_path(workout_id: @workout.id), class: "post" %> 
          <% else %>
          <%# <%= link_to "新しいワークアウトを作成", new_workout_path, class: "post" %> 
          <% end %>
        </div>
      <% else %>
        <div class="user-info">
          <span>新規登録かログインをしてトレーニングを記録しよう！</span>
        </div>
        <div class="user_nav grid-6">
          <%= link_to "ログイン", new_user_session_path, class: "login-button" %>
          <%# <%= link_to "ログイン", new_user_session_path, class: "post" %>
          <%= link_to "新規登録", new_user_registration_path, class: "login-button" %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/workouts/_exercise_fields.html.erb
<div class="nested-fields">
  <div class="field-block">
    <div class="field">
      <%= f.label :name, "トレーニング内容", class: "form-label" %>
    </div>
    <div class="field">
      <%= f.text_field :name, class: "form-input" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :weight, "負荷を入力", class: "form-label" %>
  </div>
  <div class="field">
    <%= f.number_field :weight, class: "form-input" %><span class="small-text">kg or km/h（ジョギングの場合は速さ）</span>
  </div>

  <div class="field">
    <%= f.label :reps, "回数/距離", class: "form-label" %>
  </div>
  <div class="field">
    <%= f.number_field :reps, class: "form-input" %> <span class="small-text">回 or km（ジョギングの場合は距離）</span>
  </div>

  <div class="field">
    <%= f.label :sets, "セット数", class: "form-label" %>
  </div>
  <div class="field">
    <%= f.number_field :sets, class: "form-input" %> <span class="small-text">セット</span>
  </div>

  <div class="field">
    <%= f.label :duration, "所要時間", class: "form-label" %>
  </div>
  <div class="field">
    <%= f.number_field :duration, class: "form-input" %> <span class="small-text">分</span>
  </div>
</div>

app/views/workouts/create.html.erb
<h1>Workouts#create</h1>
<p>Find me in app/views/workouts/create.html.erb</p>

app/views/workouts/destroy.html.erb
<h1>Workouts#destroy</h1>
<p>Find me in app/views/workouts/destroy.html.erb</p>

app/views/workouts/edit.html.erb
<h2>トレーニング内容を入力してください</h2>

<%= form_with(model: @workout, local: true) do |form| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>
      <ul>
        <% @workout.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="nested-fields">
    <%# "field" %>
    <div>
      <%= form.label :date, "トレーニングをした日" %>
      <%= form.date_field :date %>
    </div>
    <div>
      <%= form.label :image, "体の変化を記録する画像" %>
      <%= form.file_field :image %>
    </div>
  </div>

  <%# <div class="nested-fields"> %>
    <%# "field" %>
    <%# <%= form.label :image, "体の変化を記録する画像" %>
    <%# <%= form.file_field :image %>
  <%# </div> %>

  <div id="exercises">
    <%= form.fields_for :exercises do |exercise_form| %>
      <%= render 'exercise_fields', f: exercise_form %>
    <% end %>
  </div>

  <%# <%= link_to_add_association "トレーニングを追加する", form, :exercises %>

  <div class="actions">
    <%= form.submit "更新" %>
  </div>
<% end %>

  <div>
    <%= link_to "TOPページに戻る", root_path %>
  </div>

app/views/workouts/index.html.erb
<div class="wrapper">
  <% if user_signed_in? %>
    <%= link_to "新しいワークアウトを作成", new_workout_path, class: "new-work-button" %>

   <%# <%= form_with url: filtered_workouts_path(year: params[:year] || Time.now.year, month: params[:month] || Time.now.month), method: :get, local: true do %>
      <%# <div class="date-selector"> %>
        <%# <%= select_tag :year, options_for_select((2000..Time.now.year).to_a.reverse, selected: params[:year] || Time.now.year) %> 
        <%# <%= select_tag :month, options_for_select((1..12).to_a, selected: params[:month] || Time.now.month) %> 
        <%# <%= submit_tag "表示" %> 
       <%# </div> %>
     <%# <% end %> 
  <% end %>

  <div class="workout-list">
    <% @workouts.each do |workout| %>
      <div class="workout-card">
        <div class="workout-card-1">
          <div class="workout-date">
            <%= link_to "#{workout.date.strftime('%Y年%m月%d日')} (#{japanese_wday(workout.date)})", workout_path(workout) %>
          </div>
          <div class="workout-details">
            <span>登録者: <%= workout.user.nickname %></span>

            <!-- Display the image if attached -->
            

            <% if user_signed_in? && current_user == workout.user %>
              <div class="workout-actions">
                <%= link_to edit_workout_path(workout), class: "edit-link", data: { turbo: false } do %>
                  <span>編集</span>
                <% end %>
                <%# <%= link_to edit_workout_path(workout), class: "edit-link" do %>
                  <%# <i class="fas fa-edit"></i> 編集する %>
                <%# <% end %>
                <%= link_to workout_path(workout), data: { turbo_method: :delete, turbo: true, confirm: '削除してもよろしいですか？' }, class: "delete-link" do %>
                  <i class="fas fa-trash"></i> 削除
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="workout-image">
              <% if workout.image.attached? %>
                <%= image_tag workout.image, size: "200x200", alt: "Workout Image" %>
              <% else %>
                <p>体の変化を<br>写真で残そう！</p>
              <% end %>
        </div>

      </div>
    <% end %>
  </div>


</div>

app/views/workouts/new.html.erb
<%= form_with(model: @workout, local: true) do |form| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>
      <ul>
        <% @workout.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h2>トレーニングを追加</h2>
    <div class="nested-fields">
    <%# "field" %>
    <div>
      <%= form.label :date, "トレーニングをした日" %>
      <%= form.date_field :date %>
    </div>
    <div>
      <%= form.label :image, "体の変化を記録する画像" %>
      <%= form.file_field :image %>
    </div>
  </div>

  <div id="exercises">
    <%= form.fields_for :exercises do |exercise_form| %>
      <%= render 'exercise_fields', f: exercise_form %>
    <% end %>
  </div>

    <!-- hidden fields to include year and month params -->
  <%= form.hidden_field :year, value: params[:year] %>
  <%= form.hidden_field :month, value: params[:month] %>

  <div class="actions">
    <%= form.submit "登録" %>
  </div>
  
  
<% end %>
<div>
  <%# <%= link_to "トレーニングを追加する", new_workout_path(exercise_count: (@exercise_count || @workout.exercises.size) + 1), method: :get %>
</div>
<%= link_to "TOPページに戻る", root_path %>

app/views/workouts/show.html.erb
<div class="wrapper">
  <div class="workout-top">
    <h1><%= @workout.date.strftime("%Y年%m月%d日") %>（<%= %w(日 月 火 水 木 金 土)[@workout.date.wday] %>）のトレーニング内容が記録されました(^_^)v!</h1>
  </div>

  <% @exercises.each do |exercise| %>
    <div class="nested-fields exercise-item">
      <div class="exercise-field">
        <strong>トレーニング:</strong>
        <span><%= exercise.name %></span>
      </div>
      <div class="exercise-field">
        <strong>負荷:</strong>
        <span><%= exercise.weight %> kg or km/h（ジョギングの場合）</span>
      </div>
      <div class="exercise-field">
        <strong>回数/距離:</strong>
        <span><%= exercise.reps %> 回 or km（ジョギングの場合）</span>
      </div>
      <div class="exercise-field">
        <strong>セット数:</strong>
        <span><%= exercise.sets %> セット</span>
      </div>
      <div class="exercise-field">
        <strong>所要時間:</strong>
        <span><%= exercise.duration %> 分</span>
      </div>
    </div>
  <% end %>

  <% if @workout.image.attached? %>
    <div class="show-image">
      <%= image_tag @workout.image %>
    </div>
  <% end %>

  <% if user_signed_in? && current_user == @workout.user %>
    <div class="henshu-button">
      <%= link_to 'トレーニング内容を編集する', edit_workout_path(@workout), class: "no-link-style" %>
    </div>
  <% end %>
  <%= link_to "▶TOPページに戻る", root_path, class: "return-link" %>
</div>

app/views/workouts/update.html.erb
<h1>Workouts#update</h1>
<p>Find me in app/views/workouts/update.html.erb</p>